spin_manifest_version = 2

[application]
name = "oops-app"
version = "0.1.0"
authors = ["karthik2804 <karthik.ganeshram@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "my-app"

[component.my-app]
source = "../oops-composed.wasm"
allowed_outbound_hosts = []
files = [ "images/*" ]
